alias install='poetry install'
alias runserver='poetry run python manage.py runserver'
alias migrate='poetry run python manage.py migrate'
alias createsuperuser='poetry run python manage.py createsuperuser'
alias test='poetry run python manage.py test'
alias coverage='poetry run coverage run --source="." manage.py test && poetry run coverage report && poetry run coverage html'
alias clean='poetry run coverage erase && rm -rf htmlcov'
