# Generated by Django 4.2.4 on 2023-08-21 15:54

import apps.school.models
import apps.school.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Levels: Primary One",
                        max_length=100,
                        validators=[apps.school.validators.validate_alphabetical],
                        verbose_name="Level Name",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Levels: Pry1",
                        max_length=40,
                        verbose_name="Level Short name",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=125, unique=True, verbose_name="School Name"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=200)),
                ("motto", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, upload_to=apps.school.models.school_image_path
                    ),
                ),
                (
                    "school_type",
                    models.CharField(
                        choices=[("pr", "PRIVATE"), ("pu", "PUBLIC")],
                        default="pr",
                        max_length=20,
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=125, verbose_name="School Address"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Nigeria", max_length=100, verbose_name="Country"
                    ),
                ),
                ("state", models.CharField(max_length=100, verbose_name="State")),
                (
                    "color",
                    models.CharField(
                        max_length=20, verbose_name="School Preferred Color"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Schools",
            },
        ),
        migrations.CreateModel(
            name="SchoolAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchoolAttributes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchoolSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("slug", models.SlugField(blank=True, max_length=200)),
                (
                    "active",
                    models.BooleanField(default=False, verbose_name="School Status"),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school",
                        to="school.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "School Year",
                "verbose_name_plural": "School Years",
            },
        ),
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skill",
                    models.CharField(
                        help_text="Skills: E.g Psychomotors, Affective", max_length=100
                    ),
                ),
                (
                    "rating",
                    models.CharField(max_length=10, verbose_name="Skill Rating"),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="psychomotors",
                        to="school.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkillLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="A+, A, B", max_length=200)),
                (
                    "remark",
                    models.CharField(
                        help_text="Excellent, Very Good",
                        max_length=120,
                        verbose_name="Skill Remark",
                    ),
                ),
                (
                    "color",
                    models.CharField(max_length=120, verbose_name="color choices"),
                ),
                ("level", models.ManyToManyField(to="school.level")),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_level",
                        to="school.skills",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchoolTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="example -> First Tirm",
                        max_length=100,
                        verbose_name="Term Name",
                    ),
                ),
                ("slug", models.SlugField(blank=True)),
                ("active", models.BooleanField(default=False)),
                (
                    "term",
                    models.IntegerField(
                        choices=[
                            (1, "First Term"),
                            (2, "Second Term"),
                            (3, "Third Term"),
                        ]
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="school.schoolsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchoolSummerClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summer_class",
                        to="school.schoolsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchoolGradeScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score_name", models.CharField(max_length=30)),
                ("low_range", models.PositiveIntegerField(default=0)),
                ("upper_range", models.PositiveIntegerField()),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="school.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchoolContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=100)),
                (
                    "school_email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="School Email"
                    ),
                ),
                ("school_phone", models.CharField(max_length=20)),
                ("technical_email", models.EmailField(max_length=254, unique=True)),
                ("technical_phone", models.CharField(max_length=20)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="school.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchoolBreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "break_name",
                    models.CharField(
                        help_text="Holiday name -> Independence Day", max_length=100
                    ),
                ),
                ("slug", models.SlugField(blank=True)),
                ("is_active", models.BooleanField(default=False)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="school.schoolterm",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "School Breaks",
            },
        ),
        migrations.CreateModel(
            name="SchoolArms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arm",
                    models.CharField(help_text="Eg: A, Science, Gold", max_length=100),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_arms",
                        to="school.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LevelArms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="school.schoolarms",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="school.level",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="school.school",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Level Arms",
            },
        ),
        migrations.AddField(
            model_name="level",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="school_level",
                to="school.school",
            ),
        ),
        migrations.CreateModel(
            name="GradingSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "low_score",
                    models.PositiveIntegerField(verbose_name="score range lower"),
                ),
                (
                    "high_score",
                    models.PositiveIntegerField(verbose_name="score range higher"),
                ),
                ("grade", models.CharField(max_length=100, verbose_name="grade name")),
                (
                    "remark",
                    models.CharField(max_length=100, verbose_name="Grade Remark"),
                ),
                (
                    "teacher_comment",
                    models.CharField(max_length=250, verbose_name="Teacher's Comment"),
                ),
                (
                    "principal_comment",
                    models.CharField(
                        max_length=250, verbose_name="Principal's Comment"
                    ),
                ),
                ("level", models.ManyToManyField(to="school.level")),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grading_system",
                        to="school.school",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Grading Systems",
            },
        ),
    ]
