name: School Management Continious Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.in

      - name: Run flake8
        run: flake8 --exclude migrations .

      - name: Run black (check only)
        run: black --check .

  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.in

      - name: Run black (formatting)
        run: black .


  # deploy:
  #   needs: test
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

    # Add deployment steps here (e.g., deploy to staging/production server)

  # notifications:
  #   needs: test
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

  #   - name: Install additional dependencies
  #     run: pip install -r requirements.txt

  #   - name: Send Slack notification on failure
  #     if: ${{ failure() }}
  #     uses: rtCamp/action-slack-notify@v2
  #     with:
  #       status: failure
  #       slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
  #       channel: ${{ secrets.SLACK_CHANNEL }}
  #       text: 'Tests failed for the Django project.'

  #   - name: Create GitHub issue on failure
  #     if: ${{ failure() }}
  #     uses: peter-evans/create-issue-from-file@v2
  #     with:
  #       title: 'Tests failed for the Merge of the Pull Request'
  #       content-filepath: ./issue-template.md
